# 마우스 지원 활성화
set -g mouse on

# 스크롤 히스토리 증가
set -g history-limit 10000

# 256 color 지원
set -g default-terminal "screen-256color"
set-environment -g TERMINFO /usr/share/terminfo

# ESC 키 delay 제거
set -s escape-time 0

# 윈도우 인덱스 1부터 시작
set -g base-index 1
setw -g pane-base-index 1

# 현재 경로에서 새 창/패널 열기
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
